Add connected client metrics
charlie-haley/omada_exporter pull request #28
Opened 2022-03-05 12:14 UTC by jamiebrynes7

This PR adds a metric to track the currently connected client count.

I first looked at aggregating over the existing client metrics to derive this value.. but then realized it includes historical clients that may not be connected anymore!

2022-03-07 17:55 UTC, charlie-haley requested changes

2022-03-07 17:58 UTC, charlie-haley commented
Could you also update the `Metrics` part of the `README.md` to document the new metrics

There's a [small script](https://github.com/charlie-haley/omada_exporter/tree/main/scripts/metric-markdown-table.sh) that will do that will generate the markdown for you, based on the contents of `metrics.go` but you can also update it manually if you'd like!

2022-03-07 22:12 UTC, jamiebrynes7 commented on pkg/omada/metrics.go
> +		Name: "omada_connected_clients_count",
Done!

2022-03-08 09:05 UTC, charlie-haley approved these changes

2022-03-08 20:30 UTC, merged

2022-03-08 20:30 UTC, charlie-haley commented
Thanks for the PR, I'll send this out with the next release!